<a href="https://colab.research.google.com/github/anna01122002/ml/blob/main/%D0%91%D1%8B%D0%BA%D0%B0%D0%B4%D0%BE%D1%80%D0%BE%D0%B2%D0%B0_01_tensor_v1_0_blank.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 01. Знакомство с `torch.Tensor`

V 0.1 04.02.2021

---

При решении данных задач не подразумевается использования циклов или генераторов Python, если в задании не сказано обратного. Решение должно опираться на использование функционала библиотеки `torch`.

[PyTorch documentation](https://pytorch.org/docs/stable/#pytorch-documentation)

In [1]:
import torch

## 1.1 Создание тензоров и выполнение базовых операций над ними

[Документация по функциям для создания тензоров](https://pytorch.org/docs/stable/torch.html#creation-ops)

[Документация по функциям для работы с индексами](https://pytorch.org/docs/stable/torch.html#indexing-slicing-joining-mutating-ops)

1.1.1 Создайте двумерный тензор размера (8, 8). Используя как можно меньше операций, добейтесь расстановки кодов "шахматных фигур".

Ожидаемый результат:

```
[[-4., -3., -2., -6., -5., -2., -3., -4.],
 [-1., -1., -1., -1., -1., -1., -1., -1.],
 [0., 0., 0., 0., 0., 0., 0., 0.],
 [0., 0., 0., 0., 0., 0., 0., 0.],
 [0., 0., 0., 0., 0., 0., 0., 0.],
 [0., 0., 0., 0., 0., 0., 0., 0.],
 [1., 1., 1., 1., 1., 1., 1., 1.],
 [4., 3., 2., 6., 5., 2., 3., 4.]]

```

In [2]:
a = torch.zeros(8, 8)
a[0] = torch.tensor([-4., -3., -2., -6., -5., -2., -3., -4.])
a[1, :] = -1
a[6, :] = -a[1]
a[7, :] = -a[0]
a

tensor([[-4., -3., -2., -6., -5., -2., -3., -4.],
        [-1., -1., -1., -1., -1., -1., -1., -1.],
        [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
        [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
        [ 4.,  3.,  2.,  6.,  5.,  2.,  3.,  4.]])

1.1.2 Средствами `torch` рассчитать произведения четных чисел от 2 до 20 на ближайшие к ним бОльшие нечетные числа.

In [4]:
a = torch.arange(2, 21, 2)
print(a)
res1 = a * (a + 1)
res1

tensor([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])


tensor([  6,  20,  42,  72, 110, 156, 210, 272, 342, 420])

1.1.3 Создать тензор размера 11x7 вида: [[1, 2, 3, ..., 7], [11, 12, 13, ..., 17], [21, 22, 23, ..., 27], ..., [101, 102, 103, ..., 107]]

In [5]:
a = torch.arange(1,8)
b = torch.arange(0, 101, 10).reshape(11,1)
res2 = a + b
res2

tensor([[  1,   2,   3,   4,   5,   6,   7],
        [ 11,  12,  13,  14,  15,  16,  17],
        [ 21,  22,  23,  24,  25,  26,  27],
        [ 31,  32,  33,  34,  35,  36,  37],
        [ 41,  42,  43,  44,  45,  46,  47],
        [ 51,  52,  53,  54,  55,  56,  57],
        [ 61,  62,  63,  64,  65,  66,  67],
        [ 71,  72,  73,  74,  75,  76,  77],
        [ 81,  82,  83,  84,  85,  86,  87],
        [ 91,  92,  93,  94,  95,  96,  97],
        [101, 102, 103, 104, 105, 106, 107]])

1.1.4 Написать функцию, которая для целых значений `n` и `m` будет возвращать тензор размера `n`x`m`, заполненный текстурой размера 2x2, состоящей из следующих значений:

```
0 1

2 3

```

Пример для n = 4 и m = 5:

```
0 1 0 1 0

2 3 2 3 2

0 1 0 1 0

2 3 2 3 2
```

In [6]:
N = 4
M = 5

res = torch.zeros((N,M))
res[torch.arange(1, M, 2)] += 2
res[:, torch.arange(1, N, 2)] += 1
res

tensor([[0., 1., 0., 1., 0.],
        [2., 3., 2., 3., 2.],
        [0., 1., 0., 1., 0.],
        [2., 3., 2., 3., 2.]])

1.1.5 Сгенерировать двумерный тензор `t` размерности (4, 7), состоящий из случайных действительных чисел, равномерно распределенных в дипазоне от 0 до 20. Нормализовать значения массива с помощью преобразования вида $ax+b$ так, что после нормализации максимальный элемент масива будет равен 1.0, минимальный 0.0

[Random Sampling](https://pytorch.org/docs/stable/torch.html#random-sampling)

[Distributions](https://pytorch.org/docs/stable/distributions.html)

In [7]:
#Рандомные значения
buf = torch.rand((4, 7)) * 20
#Max-min нормализация
res = 1/(buf.max()-buf.min())*buf-buf.min()/(buf.max()-buf.min())
res

tensor([[0.4381, 0.4423, 0.4986, 0.1156, 0.8180, 0.5477, 0.3548],
        [0.1318, 0.0152, 0.7940, 0.2805, 0.9905, 0.8231, 0.8070],
        [0.6712, 1.0000, 0.8207, 0.8753, 0.6161, 0.6198, 0.4677],
        [0.1268, 0.9827, 0.5159, 0.6880, 0.6254, 0.0000, 0.4614]])

1.1.6 Задать два двумерных тензора `ar1` и `ar2` размерности (4, 7), состоящих из случайных целых чисел в пределах от 0 до 10. Построить двумерный тензор размерности (4, 7), каждый элемент которого представляет собой максимум из двух значений, находящихся на аналогичной позиции в массивах `ar1`, `ar2`.

[Reductions ops](https://pytorch.org/docs/stable/torch.html#reduction-ops)

In [8]:
#Тензор 1
ar1 = torch.randint(0, 11, size=[4, 7])
print(ar1)
#Тензор 2
ar2 = torch.randint(0, 11, size=[4, 7])
print(ar2)

res = torch.cat((ar1, ar2)).reshape((2, 4, 7)).max(axis=0).values
res

tensor([[ 4,  2,  4,  9,  3,  2,  2],
        [ 3, 10,  0, 10,  8,  8,  7],
        [ 5,  9,  2,  9,  4,  5,  9],
        [ 3,  5,  1,  2,  6,  3, 10]])
tensor([[ 8,  4,  2,  9,  3,  6,  1],
        [ 9,  0,  1,  1,  3,  8,  5],
        [ 3,  4,  9,  2,  1, 10,  6],
        [ 9,  8, 10,  0,  5,  1,  8]])


tensor([[ 8,  4,  4,  9,  3,  6,  2],
        [ 9, 10,  1, 10,  8,  8,  7],
        [ 5,  9,  9,  9,  4, 10,  9],
        [ 9,  8, 10,  2,  6,  3, 10]])

1.1.7 Создать тензор из 20 случайных целых чисел от 0 до 100. Получить второе сверху значение в тензоре. Определить индекс этого значения.

In [9]:
arr = torch.randint(0, 101, size=[20])
print(arr)
print(arr.sort().values)
print(arr.sort().values[-2])
result = arr.sort().indices[-2]
result

tensor([29, 21,  0, 20, 59, 71, 73, 94, 49, 17, 71, 49, 26, 81, 63, 66, 36, 70,
        90, 54])
tensor([ 0, 17, 20, 21, 26, 29, 36, 49, 49, 54, 59, 63, 66, 70, 71, 71, 73, 81,
        90, 94])
tensor(90)


tensor(18)

## 1.2 Распространение

[Numpy broadcasting](https://numpy.org/devdocs/user/theory.broadcasting.html)

[Torch broadcasting](https://pytorch.org/docs/stable/notes/broadcasting.html)

1.2.1 Создать тензор 11x7 вида: `[[1, 2, 3, ..., 7], [11, 12, 13, ..., 17], [21, 22, 23, ..., 27], ..., [101, 102, 103, ..., 107]]`. При решении задачи применить технику распространения.

In [10]:
first_items = torch.arange(1, 8, step=1)
print(first_items)
second_items = torch.arange(0, 101, step=10).reshape(-1, 1) 
print(second_items)
first_items + second_items

tensor([1, 2, 3, 4, 5, 6, 7])
tensor([[  0],
        [ 10],
        [ 20],
        [ 30],
        [ 40],
        [ 50],
        [ 60],
        [ 70],
        [ 80],
        [ 90],
        [100]])


tensor([[  1,   2,   3,   4,   5,   6,   7],
        [ 11,  12,  13,  14,  15,  16,  17],
        [ 21,  22,  23,  24,  25,  26,  27],
        [ 31,  32,  33,  34,  35,  36,  37],
        [ 41,  42,  43,  44,  45,  46,  47],
        [ 51,  52,  53,  54,  55,  56,  57],
        [ 61,  62,  63,  64,  65,  66,  67],
        [ 71,  72,  73,  74,  75,  76,  77],
        [ 81,  82,  83,  84,  85,  86,  87],
        [ 91,  92,  93,  94,  95,  96,  97],
        [101, 102, 103, 104, 105, 106, 107]])

1.2.2 Вычесть одномерный тензор `b_1d` из двухмерного тензора `a_2d`, так, чтобы каждый элемент одномерного тензора вычитался из всех элементов соответствующих строк двумерного тензора.

_Пример:_

Для входа:
```python
a_2d = np.array([[3,3,3],[4,4,4],[5,5,5]])
b_1d = np.array([1,2,3])
```

Ожидается резульат:

```python
[[2 2 2]
 [2 2 2]
 [2 2 2]]
```

In [11]:
b_1d = torch.tensor([1,2,3])
print(b_1d)
a_2d = torch.tensor([[3,3,3],[4,4,4],[5,5,5]])
print(a_2d)
res = a_2d - b_1d.reshape(b_1d.size()[0], 1)
res

tensor([1, 2, 3])
tensor([[3, 3, 3],
        [4, 4, 4],
        [5, 5, 5]])


tensor([[2, 2, 2],
        [2, 2, 2],
        [2, 2, 2]])

## 1.3 Индексы, маскирование и прихотливое индексирование

[Документация по функциям для работы с индексами](https://pytorch.org/docs/stable/torch.html#indexing-slicing-joining-mutating-ops)

1.3.1 Получить индексы, для которых элементы тензоров `a` и `b` совпадают.

_Пример:_

Для входа:
```python
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
```

Ожидается резульат:

```python
array([1, 3, 5, 7])
```

In [ ]:
a = torch.tensor([1,2,3,2,3,4,3,4,5,6])
b = torch.tensor([7,2,10,2,7,4,9,4,9,8])

res = (a == b).nonzero(as_tuple=True)
res[0].numpy()

1.3.2 Инвертировать порядок элементов в двумерном тензоре `torch.arange(9).view(3,3)`.

Ожидаемый результат:


```python
array([[8, 7, 6],
       [5, 4, 3],
       [2, 1, 0]])
```

In [12]:
arr = torch.arange(9).view(3,3)
arr = arr.flip(1).flip(0).numpy()
arr

array([[8, 7, 6],
       [5, 4, 3],
       [2, 1, 0]])

1.3.3 Из входного тензора a получить только элементы, находящиеся в диапазоне от 5 до 10.

_Пример:_

Для входа:
```python
a = np.array([2, 6, 1, 9, 10, 3, 27])
```

Ожидается резульат:

```python
array([6, 9, 10])
```

In [ ]:
a = torch.tensor([2, 6, 1, 9, 10, 3, 27])
mask = (a >= 5) & (a <= 10)
res = a[mask].numpy()
res

1.3.4 Поменять местами столбец 1 и 2 тензора `np.arange(9).reshape(3,3)`

In [ ]:
res = torch.arange(9).reshape(3,3)
print(res)
res = res[:, [0, 2, 1]]
res

1.3.5 Создать тензор 8 на 10 из случайных целых чисел из диапазона от 0 до 10 и найти в ней строку (ее индекс и вывести саму строку), в которой сумма значений минимальна.

In [ ]:
arr = torch.randint(0, 11, size=[8, 10])
print(arr)
item_index = arr.sum(axis=1).min(axis=0).indices.item()
print(item_index)
res = arr[item_index]
res

1.3.6 Cоздать тензор из 20 случайных целых чисел от 0 до 100. Обрезать значения тензора (заменить значения, выходящие за диапазон, на крайние значения) снизу по значению 30, сверху по значению 70.

In [ ]:
res = torch.randint(0, 101, size=[20])
print(res)
res[(res < 30)] = 30
print(res)
res[(res > 70)] = 70
res

1.3.7 Создать два тензора размера 30 на 3 из случайных целых чисел из диапазона от 0 до 10 и найти все значения первого тензора, которые больше соответсвующих (по расположению) значений второго тензора. Подсчитать сумму этих значений.

In [ ]:
a1 = torch.randint(0, 11, size=[30, 3])
a2 = torch.randint(0, 11, size=[30, 3])

mask = a1 > a2
print(a1[mask])

res = a1[mask].sum().item()
print("Sum:", res)

1.3.8 При помощи прихотливого индексирования для двухмерного массива размерности (20, 20), состоящего из случайных целых чисел в пределах от 0 до 10 получить массив элементов находящихся на диагонали, проходящей над основной диагональю.

In [ ]:
res = torch.randint(0, 11, size=[20, 20])
print(res)
print(res[torch.arange(19), torch.arange(19) +1])

1.3.9 Задать два двухмерных тензора `ar1` и `ar2` размерности (5, 10), состоящих из случайных целых чисел в пределах от 0 до 10. Удвоить все значения `ar1`, которые совпадают со значениями `ar2`, расположенными на аналогичных позициях.

In [ ]:
a1 = torch.randint(0, 11, size=[5, 10])
print(a1,"\n")
a2 = torch.randint(0, 11, size=[5, 10])
print(a2, "\n")

mask = a1 == a2
a1[mask] = a1[mask] * 2
a1

1.3.10 Заданы три двухмерных тензора `ar1`, `ar2` и `ar3` размерности (4, 7), состоящие из случайных целых чисел в пределах от 0 до 10. Обнулить все элементы `ar1`, которые больше соответствующих (находящихся в соответствующих позициях) элементов `ar2` и меньше соответствующих элементов `ar3`.

In [ ]:
a1 = torch.randint(0, 11, size=[4, 7])
print(a1, "\n")
a2 = torch.randint(0, 11, size=[4, 7])
print(a2, "\n")
a3 = torch.randint(0, 11, size=[4, 7])
print(a3, "\n")

mask = (a1 > a2) & (a1 < a3)
a1[mask] = 0
a1

1.3.11 Задан двумерный тензор `ar1` размерности (20, 5), состоящий из случайных целых чисел в пределах от 0 до 20. Определить, в каких столбцах не менее 5 раз встречается значение, максимальное по своей строке.

In [ ]:
a1 = torch.randint(0, 21, size=(20, 5))
print(a1, "\n")
condition = (a1.T == a1.max(axis=1).values).T.sum(axis=0) > 5
res = (condition).nonzero(as_tuple=True)
res[0]


1.3.12 Задан двумерный тензор `ar1` размерности (4, 7), состоящий из случайных  чисел в пределах от 0 до 1. Обнулить все значения в массиве, расположенные строго правее и ниже максимального элемента массива. 

In [ ]:
ar1 = torch.rand((4, 7))
print(ar1)
maximum = ar1.max().item()
print(maximum)

ar1[(ar1 == maximum).nonzero(as_tuple=True)[0][0] + 1:, (ar1 == maximum).nonzero(as_tuple=True)[1][0] + 1:] = 0
ar1

1.3.13 Построить "one-hot encoding" для одномерного тензора, содержащего целые числа (длина вектора заранее неизвестна, набор значений заранее неизвестен, при этом в итоговой матрице должны присутствовать столбцы для всех натуральных чисел вплоть до максимального встречающегося в исходном массиве).

Пример:

для тензора `torch.tensor([2, 3, 2, 2, 2, 1])`.

Ожидается результат:

```python
tensor([[0., 1., 0.],
        [0., 0., 1.],
        [0., 1., 0.],
        [0., 1., 0.],
        [0., 1., 0.],
        [1., 0., 0.]])
```

In [ ]:
arr = torch.tensor([2, 3, 2, 2, 2, 1])
res = torch.zeros(arr.size()[0], arr.max())
res[torch.arange(arr.size()[0]), arr-1] = 1
res

1.3.14 Создать тензор `arr` из 20 случайных целых чисел от 0 до 100. Найти самое частое значение в тензоре. 
Найти индексы в тензоре, соответствующие самому частому значению. Проверить, как работет алгоритм при двух значениях, имеющих наибольшую встречаемость, предложить приемлемое поведение алгоритма для этого случая. 

In [ ]:
arr = torch.randint(0, 101, size=[20])
print(arr)
most_value = torch.mode(arr)[0]
print(most_value)
res = (arr == most_value).nonzero(as_tuple=True)[0].tolist()
res

## 1.4 Математические задачи

1.4.1 Приблизительно (с погрешностью порядка 1%) рассчитать на какой части интервала от 0 до 10 значение функции x * sin(x) больше 0.5.

In [ ]:
n = 100000
arr = torch.linspace(0, 10, n)
print(arr)
((arr * torch.sin(arr)) > 0.5).sum() / n

1.4.2 Найти все простые числа в пределах ста. (Для решения предлагается использовать Решето Эратосфена) Использовать не более 1 цикла (желательно).

In [ ]:
arr = torch.arange(2, 101)
for item in arr:
    mask = (arr % item != 0) | (arr == item)
    arr = arr[mask]
    print(arr.tolist())
arr

1.4.3 Найти евклидово расстояние между двумя одномерными тензорами одинаковой размерности, не используя готовые решения из библиотек.

In [ ]:
x = torch.tensor([2, 3, 4, 5, 6, 7, 8, 9, 10])
y = torch.tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])


res = ((x - y) ** 2).sum().item()
res

1.4.4 Создать двумерный тензор 20 на 3, содержащий случайные целые числа от 0 до 100. 
Интерпретируя тензор как 20 векторов из 3х компонент, отсортировать его по длине векторов.

In [ ]:
arr = torch.randint(0, 101, size=[20, 3])
print(arr,"\n")

mask = (arr ** 2).sum(axis=1).sort().indices
print("mask:\n",mask)
res = arr[mask]
res

1.4.5 Найти "локальные максимумы" в одномерном тензоре (т.е. значения, большие предыдущего и последующего) `torch.tensor([1, 3, 7, 1, 2, 6, 0, 1])` и вывести их индексы.

In [ ]:
arr = torch.tensor([1, 3, 7, 10, 2, 6, 10, 1])
print(arr)

a = torch.diff(arr)[:-1]
print(a)
b = torch.diff(arr.flip(0)).flip(0)[ 1:]
print(b)

print(((a > 0) & (b > 0)).nonzero( as_tuple= True)[0] + 1)

1.4.6 Задан произвольный массив numpy (например массив из 100 случайных числе от 0 до 1). Необходимо найти в нем число наиболее близкое к заданному.

In [ ]:
arr =  torch.rand(100)
print(arr)
a = 0.52
print(a)
index = (np.abs(arr-a)).argmin()
print(arr[index])

1.4.7 Решить матричное уравнение `A*X*B=-C` - найти матрицу X. Где `A = [[-1, 2, 4], [-3, 1, 2], [-3, 0, 1]]`, `B=[[3, -1], [2, 1]]`, `C=[[7, 21], [11, 8], [8, 4]]`.

In [ ]:
A = torch.tensor([[-1., 2, 4], [-3, 1, 2], [-3, 0, 1]])
B = torch.tensor([[3., -1], [2, 1]])
C = torch.tensor([[7., 21], [11, 8], [8, 4]])
print((torch.inverse(A) @ C @ torch.inverse(B)).round())

1.4.8 Проверить, является ли система векторов a1 = (3; −3; 0; 7),
a2 = (2; 2; 4; 7), a3 = (1; 2; 3; 4), a4 = (5; −4; 1; 3) линейно зависимой?

In [ ]:
res_dict = {0: "Вектора линейно зависимы", 1: "Вектора линейно независимы"}
a1 = [3., -3, 0, 7]
a2 = [2, 2, 4, 7]
a3 = [1, 2, 3, 4]
a4 = [5, -4, 1, 3]

res = torch.tensor([a1, a2, a3, a4])
res_dict[int(res.det().round().tolist())]